service: distribution-monitoring
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  deploymentMethod: direct

functions:
  testOperators:
    handler: src/index.run
    memorySize: 256
    events:
      # Invoke Lambda function every minute
      - schedule: rate(1 minute)
    environment:
      METRICS_API_URL: https://joystream.koalva.io/operator-metrics/metrics
plugins:
  - serverless-plugin-typescript
  - serverless-offline
